### ISSUE TITLE
Remove duplicate avatar images in series of feed entries of the same user

### ISSUE THREAD

**Issue by saesh** [mjaschen/strava-helper-firefox#12]
When a user has multiple successive activity (and challange) feed entries the avatar image is repeated so many times.
- remove every avatar image but the first one in a series of the same user feed entries
- move type icon (ride, run icon under avatar image) up by adding `margin-top: -35px`

**Comment by mjaschen** [comment]
Implemented in 314216b41f578f4260fbd9f75c124a8eba5816eb

**Comment by saesh** [comment]
Great idea watching for mutations. Wondered myself how to do it, since I had the removal code ready but the loading of more activites re-rendered the avatar images.

Unfortunately this change fails on my end and successive avatar images are not being removed:

```
JPM undefined   Message: TypeError: Argument 1 of MutationObserver.observe is not an object.
```

Tested on freshly checked out master and FF39.0.

**Comment by saesh** [comment]
This causes strange behavior in my tests (OSX/FF39, Win7/FF39, Win8/FF39, Ubuntu/FF39).

When `watchFeedAutoScroll()` is enabled the following happens:
- the kudos button does not appear on the profile page
- the duplicate avatar images are not being removed (on the profile page, on dashboard it works)
- removing duplicate images after autoload does not work

I could however get the removal of duplicate images to work with the change to `index.js` in 4201c91.
