### ISSUE TITLE
Click event on segment leaderboard bubbles back to the table tr causing click-loop

### ISSUE THREAD

**Issue by saesh** [mjaschen/strava-helper-firefox#15]
The change in 6c9b71e adds a click event hanlder to `table.segments tr` that triggers a `click()`  on `.clickable[data-filter=...`. That `click()` bubbles back to the table row with the added click event handler causing an endless click-loop. The segment leaderboard filter type selection opens and closes every 100ms.

**Comment by mjaschen** [comment]
Strange, it works here as intended, but it's easy to prevent this behaviour :)

**Comment by mjaschen** [comment]
Please check if e787ff7333eb94e6a850b30f9bc5076ea80e2e57 fixes this behaviour.

**Comment by saesh** [comment]
Yes, fixed! Thanks. :+1:
