### ISSUE TITLE
Include xpi in releases not the source code

### ISSUE THREAD

**Issue by saesh** [mjaschen/strava-helper-firefox#16]
This is more a discussion topic than a question. The source is readily availble here, but the binary is not. For people who do not have the tools to build the xpi the releases should be the place to get the binary.

**Comment by mjaschen** [comment]
Releases are available at addons.mozilla.org

**Comment by mjaschen** [comment]
In a while Firefox won't allow to install unsigned extensions. Distribution of the XPI over other channels than addons.mozilla.org (AMO) will make no sense then.

I'm regularly uploading the extension updates to AMO (current status is "Waiting for Review"), last version there is 0.2.2.

[Strava Helper Extension on AMO](https://addons.mozilla.org/en-US/firefox/addon/strava-helper/)

**Comment by saesh** [comment]
> In a while Firefox won't allow to install unsigned extensions. Distribution of the XPI over other channels than addons.mozilla.org (AMO) will make no sense then.

Ok, if extensions cannot be installed outside of AMO then publishing binary releases here is superfluous.
