### ISSUE TITLE
Modularize plugin structure

### ISSUE THREAD

**Issue by saesh** [mjaschen/strava-helper-firefox#17]
Split up the mighty `strava.js` file into modules for more clearity and easy extensibility.

**Comment by saesh** [comment]
See branch `refactor_modules` for review.

**Comment by mjaschen** [comment]
![Awesome!](https://dl.dropboxusercontent.com/s/mc071tbvpl3gqo7/2015-07-13%20at%2022.28.png?dl=0)

Merged back to master, built release 0.3.0 and uploaded it to AMO.

**Comment by saesh** [comment]
![Job done!](http://www.reactiongifs.com/wp-content/uploads/2012/10/proud.gif)
