### ISSUE TITLE
Implement module for displaying notifications

### ISSUE THREAD

**Issue by saesh** [mjaschen/strava-helper-firefox#20]
Ability to display a toast notification with a message when an event occurs. Use the a `sh.pipe` event to trigger if a notification should be displayed.

**Comment by saesh** [comment]
I would suggest to use [toastr](https://github.com/CodeSeven/toastr) but it depends on jQuery.

@mjaschen are you cool with swapping out Zepto for jQuery?

**Comment by mjaschen** [comment]
Do what you have to do :-)

**Comment by saesh** [comment]
See branch `feature_notifications` for a new `ux.notifications` module.

**Comment by saesh** [comment]
This needs some more work; the autoload feature is broken. :suspect:

**Comment by saesh** [comment]
> This needs some more work; the autoload feature is broken. :suspect:

Bug has been resolved in 13ecd802.
