### ISSUE TITLE
Display progressbars in the gear table

### ISSUE THREAD

**Issue by saesh** [mjaschen/strava-helper-firefox#23]
On the athlete profile page there is a table listing all gear/bikes and the accumulated kilometers. Behind every row display a progressbar showing the relative amount of kilometers accumulated to the total amount of kilometers accross all gear/bikes.

**Comment by mjaschen** [comment]
Did I hear pie-chart? ;-)

**Comment by saesh** [comment]
Start with the progressbars, then go crazy. :laughing:
