### ISSUE TITLE
Remove "Premium" sidebar menu for non-premium users

### ISSUE THREAD

**Issue by mjaschen** [mjaschen/strava-helper-firefox#25]
It's only used for upselling and distracting.

![Premium Sidebar](https://dl.dropboxusercontent.com/s/ctwcbuqw3c3ceiv/2015-07-16%20at%2022.40.png?dl=0)

**Comment by mjaschen** [comment]
No. :-)

The sidebar is removed on activity pages from premium users, where the information is visible even for non-premium users, e. g. https://www.strava.com/activities/347901784

The sidebar should be removed only when the activity belongs to a non-premium user.

**Comment by saesh** [comment]
Ah! Did not know this is possible.
