### ISSUE TITLE
Remove "Premium" menu item on profile page

### ISSUE THREAD

**Issue by mjaschen** [mjaschen/strava-helper-firefox#26]
The "Trophy Case" link is used for upselling.

![](https://dl.dropboxusercontent.com/s/98dzobmfd1el1gp/2015-07-16%20at%2022.51.png?dl=0)

**Comment by mjaschen** [comment]
For completing this we need a tool to determine if a user is a "premium" user or not.

**Comment by saesh** [comment]
See this [comment](https://github.com/mjaschen/strava-helper-firefox/issues/25#issuecomment-122265463) in issue #25.
