### ISSUE TITLE
Nowhere obvious to set options

### ISSUE THREAD

**Issue by daFreeMan** [mjaschen/strava-helper-firefox#38]
According to the text in the Strava Helper v0.4.3 page in my installed add-ons in Firefox 56.0.1 64-bit:

`Don’t want all the features? You can fine tune Strava Helper in the add-on manager (“Preferences”).`

However, there is no `Options` or `Preferences` button available.

![sh missing option button](https://user-images.githubusercontent.com/11889733/32052600-cd4a436c-ba26-11e7-8f62-b78ab2ac9fdb.PNG)

Am I missing something obvious, or is something missing from the program?

**Comment by mjaschen** [comment]
Hi,

the preferences didn't survive the migration to the new extension format. I'm currently working on this feature - stay tuned!

**Comment by daFreeMan** [comment]
Thanks for the update!

**Comment by mjaschen** [comment]
Hi,

I've updated the extension, you can now choose your preferences. 

The update should be available in the next hour. Please wait for version 0.5.1 as the currently listed version 0.5.0 has an error with the options page, at least on Chrome.

**Comment by daFreeMan** [comment]
Works great. Thanks for the quick turnaround!
