### ISSUE TITLE
Premium options are missing

### ISSUE THREAD

**Issue by daFreeMan** [mjaschen/strava-helper-firefox#39]
I'm a premium Strava subscriber, but all the premium links seem to be blocked by Strava Helper v0.4.3 in Firefox 56.0.1 64-bit.
![sh missing premium links](https://user-images.githubusercontent.com/11889733/32052670-0249c254-ba27-11e7-9200-ccf3dd008199.PNG)

Possibly related to the fact that I can't get to the settings as noted in #38 to enable the display of my premium links.

**Comment by mjaschen** [comment]
Hi,

I've updated the extension, you can now choose in the options/preferences what is removed from the UI. The update should be available in the next hour. Please wait for version 0.5.1 as the currently listed version 0.5.0 has an error with the options page, at least on Chrome.

**Comment by daFreeMan** [comment]
Works great in Firefox. Thanks for the quick turnaround!!
