### ISSUE TITLE
possibility to hide rides commutes

### ISSUE THREAD

**Issue by lfoppiano** [mjaschen/strava-helper-firefox#40]
Hi,
   would be nice to hide rides that have been marked as commutes. This would avoid being flooded by activities that have no relevance. 

Unfortunately many strava uses don't actually flag necessarly all commutes, so this would not bring much benefits. 

I was thinking, as an idea, maybe it's worth having an option allowing hiding rides with less than 7-8 km (could be possible to make it configurable). 

What do you think?

**Comment by mjaschen** [comment]
Hi @lfoppiano 

sounds like a good idea to me. I'll implement such a filter along with an enable/disable checkbox and a configurable distance threshold field in the preferences.

**Comment by mjaschen** [comment]
Starting with version 0.6.0 you're able to remove activities tagged with “Commute”.

0.6.0 will be available in the next hours for both Firefox and Chrome.

**Comment by lfoppiano** [comment]
Thanks! I will test it as soon as I get it 👍

**Comment by lfoppiano** [comment]
@mjaschen I've tested and it doesn't seem to work. The plugin is updated and the checkbox relative to the commuting is ticked.  

I have created a new profile and created a manual activity tagged as commute: 

<img width="1242" alt="screen shot 2018-01-09 at 09 44 36" src="https://user-images.githubusercontent.com/15426/34712074-d72b4fe4-f521-11e7-938d-36f34cf9f433.png">

but then I can see it from my strava profile in the feed: 

<img width="774" alt="screen shot 2018-01-09 at 09 44 56" src="https://user-images.githubusercontent.com/15426/34712063-d27f388e-f521-11e7-94c9-afba2d4b58dd.png">

**Comment by mjaschen** [comment]
Can you send me the link to this activity? It seems that Strava doesn't mark it as “Commute” in the feed when no GPS track ist available, i. e. when no map is shown in the feed.

**Comment by lfoppiano** [comment]
Sure: https://www.strava.com/activities/1348060110 

Indeed you are right, another activity with gps information get hidden correctly: https://www.strava.com/activities/1348071869

So it works :-) 

Cheers
Luca

**Comment by mjaschen** [comment]
I'm sorry but Strava doesn't include any indicator that an activity in the feed is a commute when no map is shown. So we've to figure out another way to identify commute activities.

**Comment by lfoppiano** [comment]
I think is fine like that for the moment ;-)
