### ISSUE TITLE
Wahoo activities are filtered out

### ISSUE THREAD

**Issue by lfoppiano** [mjaschen/strava-helper-firefox#42]
Hi, 
  I've noticed that wahoo activities (outdoor) are now filtered out. Maybe the criteria to filter swift activities is related? I guess also polar activities might suffer the same problem. 

Cheers
Luca

**Comment by mjaschen** [comment]
Hi!

Thanks for opening this issue. You're right, Wahoo activities are filtered out when the “Zwift” filter is enabled.

I'll fix this and upload an updated version soon.

**Comment by mjaschen** [comment]
New version was submitted to Mozilla & Google extension directories five minutes ago.
