### ISSUE TITLE
hide Commute does not work in a language other than english

### ISSUE THREAD

**Issue by december-soul** [mjaschen/strava-helper-firefox#43]
hiding of Commute not possible because of localization.

Commute is called "Pendel" in german.
The Strave-helper calls
`        removeCommutes: function () {
            $('.activity-map-tag:contains(\'Commute\')', '.feed').parents('div.activity').remove()
        },
`
to work on the german version of the strava page the code must be changed to 

`            $('.activity-map-tag:contains(\'Pendeln\')', '.feed').parents('div.activity').remove()`

**Comment by mjaschen** [comment]
Hi,

thanks for reporting this issue.

I'll add a check for German and release a new version soon.

**Comment by mjaschen** [comment]
Update is on its way to the Firefox and Chrome extension directories and should be available soon.

**Comment by december-soul** [comment]
This is not a general solution.
But works for me :-)

**Comment by mjaschen** [comment]
Feel free to submit a pull-request which fixes it once and for all ;-)

**Comment by december-soul** [comment]
This is not a commute
```
<div class="activity-map-tags">
<div class="activity-map-tag tag-long_run">
Langer Lauf
</div>
</div>
```

```
<div class="activity-map-tags">
<div class="activity-map-tag tag-workout">
Training
</div>
</div>
```

This is a commute

```
<div class="activity-map-tags">
<div class="activity-map-tag">
Pendeln
</div>
</div>
```

So i don't know but maybe 
```
if
<div class="activity-map-tag">
is avalible
and not contains an extra class like
tag-workout or tag-long_run
```

but I wasn't looking for a bike or a swim. I don't know what the tags look like

but for now a special solution for german is ok.
