### ISSUE TITLE
zwift filtering doesn't appear to be working

### ISSUE THREAD

**Issue by Flik1** [mjaschen/strava-helper-firefox#46]
https://github.com/mjaschen/strava-helper-firefox/blob/233ee5beaf2fa53a33f4f40daf4178473ea4b750/assets/js/strava_helper.cleanup.js#L22-L34

![image](https://user-images.githubusercontent.com/11262186/92121432-9fd25980-ee3d-11ea-901c-dbdda47dbb13.png)

![image](https://user-images.githubusercontent.com/11262186/92121476-ab258500-ee3d-11ea-80c3-2b58d481798e.png)

**Comment by mjaschen** [comment]
A new version (0.11.0) fixes this issue and is submitted to the extension directories for Firefox + Chrome (reviews are pending).
