### ISSUE TITLE
Chrome: Peloton rides are deleted from Strava ride activities, even though configured to be shown in Strava Helper

### ISSUE THREAD

**Issue by RipperDrone** [mjaschen/strava-helper-firefox#50]
@wwcsig Not sure if both repos for Firefox and Chrome coexist OR if the Firefox repo is the master repo to build code for Google Chrome also, therefore posting this issue here as well: https://github.com/mjaschen/strava-helper-chrome/issues/1

**Comment by RipperDrone** [comment]
wrong repo, belonged to Chrome...

**Comment by RipperDrone** [comment]
what is strange: Strava Helper does NOT seem to save status changes of the PEloton check box: Whatever I try enabling it and then saving it, it is shown disabled when opening the options dialog nex time:
![image](https://user-images.githubusercontent.com/12601105/114320771-d7ae2780-9b17-11eb-89c2-278237a9f968.png)

All other options save their settings correctly.

Maybe this always-disabled malfunction has something to do with the bug of Peloton rides never being shown in the feed...?

**Comment by wwcsig** [comment]
@RipperDrone , I can confirm this. IMHO the code that went into the final release wasn't exactly my patch and @mjaschen added a lot of clean up but I'll take a look to see if I can find a bug here somewhere.  Clearly it is there ;)

**Comment by wwcsig** [comment]
@mjaschen  - this is indeed my bug.  Can you run a new version please sith the patch below added to strava_helper_options.js?
```
diff --git a/assets/js/strava_helper.options.js b/assets/js/strava_helper.options.js
index 8586532..b7be616 100644
--- a/assets/js/strava_helper.options.js
+++ b/assets/js/strava_helper.options.js
@@ -19,6 +19,10 @@
                 type: 'checkbox',
                 default: true
             },
+            remove_peloton_activities_from_feed: {
+                type: 'checkbox',
+                default: true
+            },
             remove_commutes_from_feed: {
                 type: 'checkbox',
                 default: false
```

**Comment by RipperDrone** [comment]
Thank you @wwcsig - yes it looked like the check box status handling routine was missing completely before, therefore no effect of any inputs :-) I tried to test the change now but realized there is more to it than just copying the bugfix code snippet into the .js file of my existing installation - it obviously needs signing / CRC checks whatever. Will test with pleasure once new version becomes available...

**Comment by mjaschen** [comment]
Thanks for bug report + pull request.

The new version (0.13.1) was submitted to the extension directories for Firefox and Chrome and should appear soon.

**Comment by RipperDrone** [comment]
Tested wrt Peloton feed on/off, works like butter now. Closing this issue... thank you both! :-)
