### ISSUE TITLE
Give Kudos to all no longer working

### ISSUE THREAD

**Issue by Kirsty99** [mjaschen/strava-helper-firefox#53]
Give Kudos to all no longer working in the latest update

**Comment by mjaschen** [comment]
Please see #52.

Extension is already fixed and available for Firefox in the Mozilla Addon Directory.

Chrome + Edge versions are waiting in the review queue.

**Comment by mjaschen** [comment]
Google has reviewed the update - version 1.1.2 is available now. "Give Kudos to All" is working again.
